apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      containers:
        - name: game-server-container
          image: rutush10/python-game-server-redis:v0.0.3
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis"        # matches redis Service name
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: "125m"
              memory: 128Mi
            limits:
              cpu: "125m"
              memory: 128Mi